import {
  PropertyData,
  ContractData,
  PaymentReceiptData,
  UtilityBillData,
  MaintenanceTicketData,
  FormalNoticeData,
  UserSession,
} from '@/types';

export const INITIAL_USERS: (UserSession & { passwordHash: string })[] = [
  {
    id: 'usr_superadmin',
    name: 'Alejandro (Superadmin Plataforma)',
    email: 'superadmin@rentacasa.com',
    role: 'SUPERADMIN',
    phone: '+34600111222',
    passwordHash: 'admin123',
  },
  {
    id: 'usr_owner1',
    name: 'Carlos Mendoza (Dueño Principal)',
    email: 'propietario@rentacasa.com',
    role: 'ADMIN',
    phone: '+34611223344',
    passwordHash: 'admin123',
  },
  {
    id: 'usr_coowner1',
    name: 'Laura Gómez (Socia Inversora 50%)',
    email: 'socio@rentacasa.com',
    role: 'CO_OWNER',
    phone: '+34622334455',
    passwordHash: 'admin123',
  },
  {
    id: 'usr_manager1',
    name: 'Marcos Rivas (Property Manager Málaga)',
    email: 'gestor@rentacasa.com',
    role: 'MANAGER',
    phone: '+34633445566',
    passwordHash: 'admin123',
  },
  {
    id: 'usr_tenant1',
    name: 'Juan Martínez',
    email: 'juan.estudiante@rentacasa.com',
    role: 'TENANT',
    phone: '+34644556677',
    passwordHash: 'admin123',
  },
  {
    id: 'usr_tenant2',
    name: 'Elena Santos',
    email: 'elena.temporal@rentacasa.com',
    role: 'TENANT',
    phone: '+34666778899',
    passwordHash: 'admin123',
  },
];

export const INITIAL_PROPERTIES: PropertyData[] = [
  {
    id: 'prop_teatinos',
    name: 'Coliving Teatinos Universidad',
    address: 'Avenida Plutarco 32, 2º B',
    city: 'Málaga',
    postalCode: '29010',
    cadastralRef: '9823412UF7692C0001TR',
    energyRating: 'B',
    energyCertUrl: 'https://ejemplo.com/cee-teatinos.pdf',
    commonAreas: 'Cocina de diseño equipada (2 frigoríficos combi, lavavajillas, horno, microondas), 2 baños completos con plato de ducha, zona comedor/salón y cuarto de lavandería con lavadora y secadora.',
    generalRules: 'Silencio riguroso de 23:00 a 08:00 h. Prohibido fumar en todo el inmueble. No se admiten mascotas ni celebración de fiestas. Las visitas no pueden pernoctar más de 2 noches consecutivas.',
    wifiName: 'Teatinos_Coliving_5G',
    wifiPassword: 'MalagaFibra2025!',
    ownerId: 'usr_owner1',
    ownerName: 'Carlos Mendoza',
    coOwners: [
      {
        userId: 'usr_coowner1',
        userName: 'Laura Gómez',
        userEmail: 'socio@rentacasa.com',
        percentage: 50.0,
      },
    ],
    fixedExpenses: [
      { id: 'fe1', concept: 'Comunidad de Propietarios', amount: 85.0, frequency: 'MONTHLY' },
      { id: 'fe2', concept: 'IBI Ayuntamiento de Málaga', amount: 520.0, frequency: 'ANNUAL' },
      { id: 'fe3', concept: 'Seguro Multirriesgo e Impago', amount: 340.0, frequency: 'ANNUAL' },
      { id: 'fe4', concept: 'Fibra Óptica 1Gb Simétrica', amount: 39.99, frequency: 'MONTHLY' },
      { id: 'fe5', concept: 'Servicio Limpieza Zonas Comunes', amount: 150.0, frequency: 'MONTHLY' },
    ],
    units: [
      {
        id: 'unit_h1',
        propertyId: 'prop_teatinos',
        propertyName: 'Coliving Teatinos Universidad',
        name: 'Habitación 1 - Exterior con Balcón',
        type: 'ROOM',
        surfaceArea: 16.5,
        bedType: 'Doble (135x190 cm con canapé)',
        hasDesk: true,
        privateBathroom: false,
        baseRent: 550.0,
        depositAmount: 550.0,
        utilityCap: 35.0,
        status: 'OCCUPIED',
        currentContract: {
          id: 'ct_juan',
          tenantName: 'Juan Martínez',
          tenantPhone: '+34644556677',
          startDate: '2025-09-01',
          endDate: '2026-06-30',
        },
      },
      {
        id: 'unit_h2',
        propertyId: 'prop_teatinos',
        propertyName: 'Coliving Teatinos Universidad',
        name: 'Habitación 2 - Suite con Baño Privado',
        type: 'ROOM',
        surfaceArea: 20.0,
        bedType: 'Queen (150x200 cm con canapé)',
        hasDesk: true,
        privateBathroom: true,
        baseRent: 650.0,
        depositAmount: 650.0,
        utilityCap: 35.0,
        status: 'OCCUPIED',
        currentContract: {
          id: 'ct_elena',
          tenantName: 'Elena Santos',
          tenantPhone: '+34666778899',
          startDate: '2025-10-01',
          endDate: '2026-02-28', // Fin primer cuatrimestre UMA
        },
      },
      {
        id: 'unit_h3',
        propertyId: 'prop_teatinos',
        propertyName: 'Coliving Teatinos Universidad',
        name: 'Habitación 3 - Interior Tranquila',
        type: 'ROOM',
        surfaceArea: 13.0,
        bedType: 'Individual Grande (105x190 cm)',
        hasDesk: true,
        privateBathroom: false,
        baseRent: 450.0,
        depositAmount: 450.0,
        utilityCap: 35.0,
        status: 'AVAILABLE',
      },
      {
        id: 'unit_h4',
        propertyId: 'prop_teatinos',
        propertyName: 'Coliving Teatinos Universidad',
        name: 'Habitación 4 - Luminosa Vista Abierta',
        type: 'ROOM',
        surfaceArea: 14.5,
        bedType: 'Doble (135x190 cm)',
        hasDesk: true,
        privateBathroom: false,
        baseRent: 490.0,
        depositAmount: 490.0,
        utilityCap: 35.0,
        status: 'RESERVED',
      },
    ],
  },
  {
    id: 'prop_soho',
    name: 'Estudio Soho Tech Málaga',
    address: 'Calle Tomás Heredia 14, 1º Izquierda',
    city: 'Málaga',
    postalCode: '29001',
    cadastralRef: '8392104UF6810B0002RE',
    energyRating: 'C',
    commonAreas: 'Portal y ascensor comunitario.',
    generalRules: 'Alquiler temporal para trabajadores desplazados en Málaga TechPark (PTA) o nómadas digitales. Prohibido subarriendo turístico tipo Airbnb.',
    wifiName: 'Soho_Tech_Malaga_Fibra',
    wifiPassword: 'StudioSoho2025!',
    ownerId: 'usr_owner1',
    ownerName: 'Carlos Mendoza',
    coOwners: [],
    fixedExpenses: [
      { id: 'fe10', concept: 'Comunidad Mensual', amount: 50.0, frequency: 'MONTHLY' },
      { id: 'fe11', concept: 'IBI Ayuntamiento de Málaga', amount: 320.0, frequency: 'ANNUAL' },
      { id: 'fe12', concept: 'Seguro Multirriesgo', amount: 210.0, frequency: 'ANNUAL' },
    ],
    units: [
      {
        id: 'unit_apt1',
        propertyId: 'prop_soho',
        propertyName: 'Estudio Soho Tech Málaga',
        name: 'Apartamento Soho Completo',
        type: 'APARTMENT',
        surfaceArea: 42.0,
        bedType: 'Cama doble 150cm',
        hasDesk: true,
        privateBathroom: true,
        baseRent: 950.0,
        depositAmount: 950.0,
        utilityCap: 0.0, // Repercusión íntegra de luz/agua
        electricMeterNumber: 'ES002100000489123847',
        status: 'AVAILABLE',
      },
    ],
  },
];

export const INITIAL_CONTRACTS: ContractData[] = [
  {
    id: 'ct_juan',
    unitId: 'unit_h1',
    unitName: 'Habitación 1 - Exterior con Balcón',
    propertyId: 'prop_teatinos',
    propertyName: 'Coliving Teatinos Universidad',
    tenantId: 'usr_tenant1',
    tenantName: 'Juan Martínez',
    tenantEmail: 'juan.estudiante@rentacasa.com',
    tenantPhone: '+34644556677',
    tenantDocType: 'DNI',
    tenantDocNumber: '48923145X',
    tenantPermanentCity: 'Sevilla (España)',
    startDate: '2025-09-01',
    endDate: '2026-06-30',
    monthlyRent: 550.0,
    depositAmount: 550.0,
    utilityCap: 35.0,
    temporalCauseType: 'STUDIES',
    temporalCauseDetail: 'Matrícula en Máster Universitario en Ingeniería del Software e Inteligencia Artificial - Universidad de Málaga (UMA) - Campus de Teatinos (Curso 2025-2026)',
    temporalCauseDocUrl: 'https://ejemplo.com/matricula-uma-juan.pdf',
    status: 'ACTIVE',
    magicToken: 'tk_8f9a2b4c6e0d1f3a5b7c9e2d4f6a8b0c1d3e5f7a9b8c7d6e',
    magicTokenExpiresAt: '2027-01-01T00:00:00.000Z',
    signedAt: '2025-08-28T18:30:00.000Z',
    signerIp: '88.12.45.192',
    signerUserAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari',
    signatureSvg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><path d="M10 40 Q 30 10, 60 30 T 110 25 T 160 35 T 190 20" fill="none" stroke="#0f766e" stroke-width="2.5"/></svg>',
    auditTrail: {
      timestampUtc: '2025-08-28T18:30:00.000Z',
      publicIp: '88.12.45.192',
      userAgent: 'iPhone iOS 17.4 Mobile Safari (Málaga, Andalucía)',
      contractHashSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      eidasValidationStatus: 'ADVANCED_ELECTRONIC_SIGNATURE_EIDAS_COMPLIANT',
    },
    inventoryVerifiedAt: '2025-09-02T11:00:00.000Z',
    keyDeliveryDate: '2025-09-01T12:00:00.000Z',
    deposit: {
      id: 'dep_juan',
      amountHeld: 550.0,
      regionalDepositRef: 'AVRA-MA-2025-098124', // Resguardo oficial Junta de Andalucía
      status: 'HELD',
    },
  },
  {
    id: 'ct_elena',
    unitId: 'unit_h2',
    unitName: 'Habitación 2 - Suite con Baño Privado',
    propertyId: 'prop_teatinos',
    propertyName: 'Coliving Teatinos Universidad',
    tenantId: 'usr_tenant2',
    tenantName: 'Elena Santos',
    tenantEmail: 'elena.temporal@rentacasa.com',
    tenantPhone: '+34666778899',
    tenantDocType: 'DNI',
    tenantDocNumber: '53112233Y',
    tenantPermanentCity: 'Valencia (España)',
    startDate: '2025-10-01',
    endDate: '2026-02-28',
    monthlyRent: 650.0,
    depositAmount: 650.0,
    utilityCap: 35.0,
    temporalCauseType: 'WORK_CONTRACT',
    temporalCauseDetail: 'Contrato laboral temporal para proyecto en empresa tecnológica en Málaga TechPark (Parque Tecnológico de Andalucía - PTA).',
    temporalCauseDocUrl: 'https://ejemplo.com/contrato-trabajo-pta-elena.pdf',
    status: 'ACTIVE',
    magicToken: 'tk_3d7e1b9a5f8c2e4a6b0d9f1c3e5a7b9c1d3e5f7a2b4c6e8d',
    magicTokenExpiresAt: '2027-01-01T00:00:00.000Z',
    signedAt: '2025-09-29T16:15:00.000Z',
    signerIp: '83.50.199.14',
    signerUserAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0.0.0 Safari/537.36',
    signatureSvg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><path d="M15 35 Q 40 15, 80 40 T 130 15 T 185 30" fill="none" stroke="#0f766e" stroke-width="2.5"/></svg>',
    auditTrail: {
      timestampUtc: '2025-09-29T16:15:00.000Z',
      publicIp: '83.50.199.14',
      userAgent: 'Windows 10 Chrome 128 (Málaga, Andalucía)',
      contractHashSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
      eidasValidationStatus: 'ADVANCED_ELECTRONIC_SIGNATURE_EIDAS_COMPLIANT',
    },
    deposit: {
      id: 'dep_elena',
      amountHeld: 650.0,
      regionalDepositRef: 'AVRA-MA-2025-081290', // Resguardo oficial Junta de Andalucía
      status: 'HELD',
    },
  },
];

export const INITIAL_PAYMENTS: PaymentReceiptData[] = [
  {
    id: 'pay_1',
    contractId: 'ct_juan',
    tenantId: 'usr_tenant1',
    tenantName: 'Juan Martínez',
    tenantPhone: '+34644556677',
    propertyName: 'Coliving Teatinos Universidad',
    unitName: 'Habitación 1 - Exterior',
    month: 9,
    year: 2025,
    rentAmount: 550.0,
    utilitiesAmount: 14.50,
    totalAmount: 564.50,
    status: 'PAID',
    paymentDate: '2025-09-03',
    paymentMethod: 'TRANSFER',
    notes: 'Transferencia bancaria recibida en cuenta corriente.',
  },
  {
    id: 'pay_2',
    contractId: 'ct_juan',
    tenantId: 'usr_tenant1',
    tenantName: 'Juan Martínez',
    tenantPhone: '+34644556677',
    propertyName: 'Coliving Teatinos Universidad',
    unitName: 'Habitación 1 - Exterior',
    month: 10,
    year: 2025,
    rentAmount: 550.0,
    utilitiesAmount: 0.0,
    totalAmount: 550.0,
    status: 'PENDING',
    notes: 'En plazo ordinario (días 1 al 5 del mes).',
  },
  {
    id: 'pay_3',
    contractId: 'ct_elena',
    tenantId: 'usr_tenant2',
    tenantName: 'Elena Santos',
    tenantPhone: '+34666778899',
    propertyName: 'Coliving Teatinos Universidad',
    unitName: 'Habitación 2 - Suite',
    month: 10,
    year: 2025,
    rentAmount: 650.0,
    utilitiesAmount: 22.50,
    totalAmount: 672.50,
    status: 'OVERDUE', // En rojo para disparar el recordatorio por WhatsApp
    notes: 'Pago pendiente vencido el día 5.',
  },
];

export const INITIAL_UTILITY_BILLS: UtilityBillData[] = [
  {
    id: 'bill_oct2025',
    propertyId: 'prop_teatinos',
    propertyName: 'Coliving Teatinos Universidad',
    type: 'ELECTRICITY',
    invoiceNumber: 'FAC-ENDE-2025-09812',
    periodStart: '2025-09-01',
    periodEnd: '2025-09-30',
    totalAmount: 169.0,
    invoicePdfUrl: 'https://ejemplo.com/factura-luz-malaga-sep2025.pdf',
    charges: [
      {
        contractId: 'ct_juan',
        tenantName: 'Juan Martínez',
        unitName: 'Habitación 1 - Exterior',
        proratedDays: 30,
        amountCharged: 49.50,
        calculationDetail: 'Factura 169€ - Bolsa de topes 70€ = Exceso 99€ / 2 habitaciones activas = 49.50€',
      },
      {
        contractId: 'ct_elena',
        tenantName: 'Elena Santos',
        unitName: 'Habitación 2 - Suite',
        proratedDays: 30,
        amountCharged: 49.50,
        calculationDetail: 'Factura 169€ - Bolsa de topes 70€ = Exceso 99€ / 2 habitaciones activas = 49.50€',
      },
    ],
  },
];

export const INITIAL_TICKETS: MaintenanceTicketData[] = [
  {
    id: 'tkt_1',
    propertyId: 'prop_teatinos',
    propertyName: 'Coliving Teatinos Universidad',
    unitId: 'unit_h1',
    unitName: 'Habitación 1 - Exterior',
    reportedById: 'usr_tenant1',
    reportedByName: 'Juan Martínez',
    reportedByPhone: '+34644556677',
    title: 'Persiana del balcón encallada',
    description: 'La cinta de la persiana exterior no sube por completo en Av. Plutarco, se queda a media altura.',
    isCommonArea: false,
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    photos: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=60'],
    createdAt: '2025-09-12T10:15:00.000Z',
  },
  {
    id: 'tkt_2',
    propertyId: 'prop_teatinos',
    propertyName: 'Coliving Teatinos Universidad',
    reportedById: 'usr_tenant2',
    reportedByName: 'Elena Santos',
    reportedByPhone: '+34666778899',
    title: 'Ligera fuga en grifo del fregadero',
    description: 'Gotea levemente por la junta inferior del monomando de la cocina común.',
    isCommonArea: true,
    priority: 'LOW',
    status: 'REPORTED',
    photos: [],
    createdAt: '2025-09-20T17:40:00.000Z',
  },
];

export const INITIAL_NOTICES: FormalNoticeData[] = [
  {
    id: 'not_1',
    propertyId: 'prop_teatinos',
    propertyName: 'Coliving Teatinos Universidad',
    senderName: 'Carlos Mendoza (Dueño)',
    title: 'Revisión Técnica Anual de Climatización y Gas',
    message: 'Estimados inquilinos: el próximo jueves entre las 10:00 y las 12:00 h acudirá el técnico autorizado para la revisión reglamentaria de los equipos de climatización del inmueble en Teatinos.',
    urgencyLevel: 'IMPORTANT',
    createdAt: '2025-09-15T09:00:00.000Z',
    reads: [
      {
        tenantId: 'usr_tenant1',
        tenantName: 'Juan Martínez',
        readAt: '2025-09-15T11:22:00.000Z',
        readerIp: '88.12.45.192',
      },
    ],
  },
];
